/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteSareesRouteImport } from './routes/_site/sarees'
import { Route as SiteRentalsRouteImport } from './routes/_site/rentals'
import { Route as SiteLehengasRouteImport } from './routes/_site/lehengas'
import { Route as SiteGalleryRouteImport } from './routes/_site/gallery'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCelebrityRouteImport } from './routes/_site/celebrity'
import { Route as SiteBridalRouteImport } from './routes/_site/bridal'
import { Route as SiteBlogRouteImport } from './routes/_site/blog'
import { Route as SiteAppointmentRouteImport } from './routes/_site/appointment'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteProductSlugRouteImport } from './routes/_site/product.$slug'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSareesRoute = SiteSareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRentalsRoute = SiteRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLehengasRoute = SiteLehengasRouteImport.update({
  id: '/lehengas',
  path: '/lehengas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGalleryRoute = SiteGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCelebrityRoute = SiteCelebrityRouteImport.update({
  id: '/celebrity',
  path: '/celebrity',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBridalRoute = SiteBridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAppointmentRoute = SiteAppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductSlugRoute = SiteProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/appointment': typeof SiteAppointmentRoute
  '/blog': typeof SiteBlogRouteWithChildren
  '/bridal': typeof SiteBridalRoute
  '/celebrity': typeof SiteCelebrityRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/lehengas': typeof SiteLehengasRoute
  '/rentals': typeof SiteRentalsRoute
  '/sarees': typeof SiteSareesRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/appointment': typeof SiteAppointmentRoute
  '/blog': typeof SiteBlogRouteWithChildren
  '/bridal': typeof SiteBridalRoute
  '/celebrity': typeof SiteCelebrityRoute
  '/contact': typeof SiteContactRoute
  '/gallery': typeof SiteGalleryRoute
  '/lehengas': typeof SiteLehengasRoute
  '/rentals': typeof SiteRentalsRoute
  '/sarees': typeof SiteSareesRoute
  '/': typeof SiteIndexRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/appointment': typeof SiteAppointmentRoute
  '/_site/blog': typeof SiteBlogRouteWithChildren
  '/_site/bridal': typeof SiteBridalRoute
  '/_site/celebrity': typeof SiteCelebrityRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/gallery': typeof SiteGalleryRoute
  '/_site/lehengas': typeof SiteLehengasRoute
  '/_site/rentals': typeof SiteRentalsRoute
  '/_site/sarees': typeof SiteSareesRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/product/$slug': typeof SiteProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/blog'
    | '/bridal'
    | '/celebrity'
    | '/contact'
    | '/gallery'
    | '/lehengas'
    | '/rentals'
    | '/sarees'
    | '/blog/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/appointment'
    | '/blog'
    | '/bridal'
    | '/celebrity'
    | '/contact'
    | '/gallery'
    | '/lehengas'
    | '/rentals'
    | '/sarees'
    | '/'
    | '/blog/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/appointment'
    | '/_site/blog'
    | '/_site/bridal'
    | '/_site/celebrity'
    | '/_site/contact'
    | '/_site/gallery'
    | '/_site/lehengas'
    | '/_site/rentals'
    | '/_site/sarees'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sarees': {
      id: '/_site/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SiteSareesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/rentals': {
      id: '/_site/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof SiteRentalsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lehengas': {
      id: '/_site/lehengas'
      path: '/lehengas'
      fullPath: '/lehengas'
      preLoaderRoute: typeof SiteLehengasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/gallery': {
      id: '/_site/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGalleryRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/celebrity': {
      id: '/_site/celebrity'
      path: '/celebrity'
      fullPath: '/celebrity'
      preLoaderRoute: typeof SiteCelebrityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bridal': {
      id: '/_site/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof SiteBridalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/appointment': {
      id: '/_site/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof SiteAppointmentRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/product/$slug': {
      id: '/_site/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof SiteProductSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteBlogRoute
    }
  }
}

interface SiteBlogRouteChildren {
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
}

const SiteBlogRouteChildren: SiteBlogRouteChildren = {
  SiteBlogSlugRoute: SiteBlogSlugRoute,
}

const SiteBlogRouteWithChildren = SiteBlogRoute._addFileChildren(
  SiteBlogRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAppointmentRoute: typeof SiteAppointmentRoute
  SiteBlogRoute: typeof SiteBlogRouteWithChildren
  SiteBridalRoute: typeof SiteBridalRoute
  SiteCelebrityRoute: typeof SiteCelebrityRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteGalleryRoute: typeof SiteGalleryRoute
  SiteLehengasRoute: typeof SiteLehengasRoute
  SiteRentalsRoute: typeof SiteRentalsRoute
  SiteSareesRoute: typeof SiteSareesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductSlugRoute: typeof SiteProductSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAppointmentRoute: SiteAppointmentRoute,
  SiteBlogRoute: SiteBlogRouteWithChildren,
  SiteBridalRoute: SiteBridalRoute,
  SiteCelebrityRoute: SiteCelebrityRoute,
  SiteContactRoute: SiteContactRoute,
  SiteGalleryRoute: SiteGalleryRoute,
  SiteLehengasRoute: SiteLehengasRoute,
  SiteRentalsRoute: SiteRentalsRoute,
  SiteSareesRoute: SiteSareesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductSlugRoute: SiteProductSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
